version: "3.8"

services:

  backend-apollo:
    tty: true
    stdin_open: true
    build:
      context: ./backend-apollo
      dockerfile: ./Dockerfile
    ports: 
      - 4000:4000
    depends_on:
      - database
    env_file: ./backend-apollo/.env
    restart: on-failure

  database:
    build:
      context: ./database
      dockerfile: ./Dockerfile
    env_file: ./database/.env
    ports:
      - 5432:5432
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    env_file: ./frontend/.env
    ports: 
      - 3000:3000
    depends_on:
      - backend-apollo
    restart: on-failure

  